
%% All ROIs
inp = struct( ...
    'hpf_sec', '300', ...
    'fwhm_mm', '6', ...
    'motpar1_txt', '../../OUTPUTS/rfmri1.par', ...
    'motpar2_txt', '../../OUTPUTS/rfmri2.par', ...
    'motpar3_txt', '../../OUTPUTS/rfmri3.par', ...
    'motpar4_txt', '../../OUTPUTS/rfmri4.par', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/ctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/ctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/ctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/ctrrfmri4.nii', ...
    'meanfmri_nii', '../../OUTPUTS/ctrrfmri_mean_all.nii', ...
    'deffwd_nii', '../../OUTPUTS/y_deffwd.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii', ...
    'refimg_nii', 'avg152T1.nii', ...
    'out_dir', '../../OUTPUTS' ...
    );
matlab_main_ppi(inp);



%%
spm('defaults','fmri')
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii' ...
    );

first_level_stats_hct(inp);



%%
spm('defaults','fmri')
inp = struct( ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct', ...
    'voi_label_image', '../../OUTPUTS-ppitest/atlas-BAISins_space-MNI152NLin6Asym_res-02_dseg.nii', ...
    'voi_label_index', 1, ...
    'voi_name', 'dAI_L' ...
    );
create_ppi_regressors(inp);


%%
spm('defaults','fmri')
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii', ...
    'voi_name', 'dAI_L', ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct', ...
    'ppi_con', 'Heart_gt_Counting' ...
    );

first_level_stats_hct_ppi(inp);

% Contrasts:
% 5  'dAI_L'
% 6  'PPI_Heart_dAI_L'
% 7  'PPI_Counting_dAI_L'
% 8  'PPI_Heart_plus_Counting_dAI_L'
% 9  'PPI_Heart_gt_Counting_dAI_L'


%%
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii', ...
    'voi_name', 'dAI_L', ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct' ...
    );

first_level_stats_hct_manppi(inp);

% Contrasts:
% 5  'HeartConn_dAI_L'
% 6  'CountingConn_dAI_L'
% 7  'HeartConn_plus_CountingConn_dAI_L'
% 8  'HeartConn_gt_CountingConn_dAI_L'

