
%%
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii' ...
    );

first_level_stats_hct(inp);



%%
inp = struct( ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct', ...
    'voi_label_image', '../../OUTPUTS-ppitest/atlas-BAISins_space-MNI152NLin6Asym_res-02_dseg.nii', ...
    'voi_label_index', 1, ...
    'voi_name', 'dAI_L' ...
    );
create_ppi_regressors(inp);


%%
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii', ...
    'voi_name', 'dAI_L', ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct', ...
    'ppi_con', 'Heart_gt_Counting' ...
    );

first_level_stats_hct_ppi(inp);




%%
inp = struct( ...
    'hpf_sec', '300', ...
    'motpar1_txt', '../../OUTPUTS/motpar1.txt', ...
    'motpar2_txt', '../../OUTPUTS/motpar2.txt', ...
    'motpar3_txt', '../../OUTPUTS/motpar3.txt', ...
    'motpar4_txt', '../../OUTPUTS/motpar4.txt', ...
    'out_dir', '../../OUTPUTS', ...
    'eprime_csv', '../../OUTPUTS/eprime.csv', ...
    'fmri1_nii', '../../OUTPUTS/swctrrfmri1.nii', ...
    'fmri2_nii', '../../OUTPUTS/swctrrfmri2.nii', ...
    'fmri3_nii', '../../OUTPUTS/swctrrfmri3.nii', ...
    'fmri4_nii', '../../OUTPUTS/swctrrfmri4.nii', ...
    'biasnorm_nii', '../../OUTPUTS/biasnorm.nii', ...
    'voi_name', 'dAI_L', ...
    'spm_dir', '../../OUTPUTS/spm_hct', ...
    'ppi_dir', '../../OUTPUTS/ppi_hct' ...
    );

first_level_stats_hct_manppi(inp);

